### ISSUE TITLE
example "Hello XDP" run error "Segmentation fault" on centos9 stream and ubuntu 22.04 x86_64 

### ISSUE THREAD

**Issue by shenshouer** [aya-rs/aya#377] opened 2022-09-01 09:51 UTC
on centos9
```
[sudo] password for sope: 
[2022-09-01T09:49:35Z DEBUG aya::bpf] [FEAT PROBE] BPF program name support: true
[2022-09-01T09:49:35Z DEBUG aya::bpf] [FEAT PROBE] BTF support: true
[2022-09-01T09:49:35Z DEBUG aya::bpf] [FEAT PROBE] BTF func support: true
[2022-09-01T09:49:35Z DEBUG aya::bpf] [FEAT PROBE] BTF global func support: true
[2022-09-01T09:49:35Z DEBUG aya::bpf] [FEAT PROBE] BTF var and datasec support: true
[2022-09-01T09:49:35Z DEBUG aya::bpf] [FEAT PROBE] BTF float support: true
[2022-09-01T09:49:35Z DEBUG aya::bpf] [FEAT PROBE] BTF decl_tag support: true
[2022-09-01T09:49:35Z DEBUG aya::bpf] [FEAT PROBE] BTF type_tag support: false
[2022-09-01T09:49:35Z DEBUG aya::obj::relocation] relocating program myapp function myapp
[2022-09-01T09:49:35Z DEBUG aya::obj::relocation] finished relocating program myapp function myapp
[2022-09-01T09:49:35Z TRACE mio::poll] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
[2022-09-01T09:49:35Z TRACE mio::poll] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
[2022-09-01T09:49:35Z TRACE mio::poll] registering event source with poller: token=Token(3), interests=READABLE | WRITABLE
[2022-09-01T09:49:35Z TRACE mio::poll] registering event source with poller: token=Token(4), interests=READABLE | WRITABLE
[2022-09-01T09:49:35Z INFO  myapp] Waiting for Ctrl-C...
Segmentation fault
[sope@centos-stream myapp]$ uname -a
Linux centos-stream 5.14.0-148.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 19 13:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

on ubuntu
```
       Fresh aya-log-ebpf-macros v0.1.0 (https://github.com/aya-rs/aya?branch=main#906c25ff)
       Fresh aya-log-ebpf v0.1.0 (https://github.com/aya-rs/aya?branch=main#906c25ff)
       Fresh myapp-ebpf v0.1.0 (/home/sope/workspaces/rust/myapp/myapp-ebpf)
    Finished dev [optimized] target(s) in 0.27s
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
[sudo] password for sope: 
[2022-09-01T09:50:22Z DEBUG aya::bpf] [FEAT PROBE] BPF program name support: true
[2022-09-01T09:50:22Z DEBUG aya::bpf] [FEAT PROBE] BTF support: true
[2022-09-01T09:50:22Z DEBUG aya::bpf] [FEAT PROBE] BTF func support: true
[2022-09-01T09:50:22Z DEBUG aya::bpf] [FEAT PROBE] BTF global func support: true
[2022-09-01T09:50:22Z DEBUG aya::bpf] [FEAT PROBE] BTF var and datasec support: true
[2022-09-01T09:50:22Z DEBUG aya::bpf] [FEAT PROBE] BTF float support: true
[2022-09-01T09:50:22Z DEBUG aya::bpf] [FEAT PROBE] BTF decl_tag support: false
[2022-09-01T09:50:22Z DEBUG aya::bpf] [FEAT PROBE] BTF type_tag support: false
[2022-09-01T09:50:22Z DEBUG aya::obj::relocation] relocating program myapp function myapp
[2022-09-01T09:50:22Z DEBUG aya::obj::relocation] finished relocating program myapp function myapp
[2022-09-01T09:50:22Z TRACE mio::poll] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
[2022-09-01T09:50:22Z TRACE mio::poll] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
[2022-09-01T09:50:22Z TRACE mio::poll] registering event source with poller: token=Token(3), interests=READABLE | WRITABLE
[2022-09-01T09:50:22Z TRACE mio::poll] registering event source with poller: token=Token(4), interests=READABLE | WRITABLE
[2022-09-01T09:50:22Z INFO  myapp] Waiting for Ctrl-C...
Segmentation fault
sope@sope-vbox:~/workspaces/rust/myapp$ uname -a
Linux sope-vbox 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dave-tucker** [comment] 2022-09-01 10:50
Installed an Ubuntu VM and copied over the object file from my local machine.
Works fine on Ubuntu 22.04 as far as I can tell.

```
dave in 🌐 ubuntu in ~ 
❯ RUST_LOG=debug sudo ./myapp --iface enp1s0
10:40:20 [DEBUG] (1) aya::bpf: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/bpf.rs:135] [FEAT PROBE] BPF program name support: true
10:40:20 [DEBUG] (1) aya::bpf: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/bpf.rs:138] [FEAT PROBE] BTF support: true
10:40:20 [DEBUG] (1) aya::bpf: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/bpf.rs:142] [FEAT PROBE] BTF func support: true
10:40:20 [DEBUG] (1) aya::bpf: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/bpf.rs:145] [FEAT PROBE] BTF global func support: true
10:40:20 [DEBUG] (1) aya::bpf: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/bpf.rs:151] [FEAT PROBE] BTF var and datasec support: true
10:40:20 [DEBUG] (1) aya::bpf: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/bpf.rs:157] [FEAT PROBE] BTF float support: true
10:40:20 [DEBUG] (1) aya::bpf: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/bpf.rs:160] [FEAT PROBE] BTF decl_tag support: false
10:40:20 [DEBUG] (1) aya::bpf: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/bpf.rs:163] [FEAT PROBE] BTF type_tag support: false
10:40:20 [DEBUG] (1) aya::obj::relocation: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/obj/relocation.rs:270] relocating program myapp function myapp
10:40:20 [DEBUG] (1) aya::obj::relocation: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/obj/relocation.rs:327] relocating call to callee address 64 (relocation)
10:40:20 [DEBUG] (1) aya::obj::relocation: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/obj/relocation.rs:348] callee is memcpy
10:40:20 [DEBUG] (1) aya::obj::relocation: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/obj/relocation.rs:270] relocating program myapp function memcpy
10:40:20 [DEBUG] (1) aya::obj::relocation: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/obj/relocation.rs:363] finished relocating program myapp function memcpy
10:40:20 [DEBUG] (1) aya::obj::relocation: [/home/dave/.cargo/git/checkouts/aya-c55fbc69175ac116/66b4f79/aya/src/obj/relocation.rs:363] finished relocating program myapp function myapp
10:40:20 [INFO] myapp: [myapp/src/main.rs:52] Waiting for Ctrl-C...
10:40:20 [INFO] myapp: [src/main.rs:22] received a packet

dave in 🌐 ubuntu in ~ 
❯ uname -a
Linux ubuntu 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I think to debug this further we'll need to know where the crash is coming from.
If you could add some log statements of `println!` into `main.rs` we might be able to see what's happening.

/cc @vadorovsky as if I were a gambler, I'd bet on aya-log :game_die:

**Comment by vadorovsky** [comment] 2022-09-01 11:14
@dave-tucker I'm 100% sure that's because we didn't release a new version of aya-log with format hints. So if someone creates a new project with aya-template now, they will end up with:

* userspace project using aya-log from crates.io **without** format hints
* eBPF project using aya-log-ebpf from git **with** format hints

Therefore eBPF program will keep sending fragmented literals with format hints, which are not expected by aya-log in userspace, therefore it's segfaulting.

**Comment by vadorovsky** [comment] 2022-09-01 11:15
@shenshouer A temporary fix which works for me is applying the following diff on new projects:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index da00d7a..c915314 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -1,2 +1,5 @@
 [workspace]
 members = ["mkdir", "mkdir-common", "xtask"]
+
+[patch.crates-io]
+aya = { git = "https://github.com/aya-rs/aya", branch = "main", features = ["async_tokio"] }
diff --git a/mkdir/Cargo.toml b/mkdir/Cargo.toml
index 41b9ab5..44429fe 100644
--- a/mkdir/Cargo.toml
+++ b/mkdir/Cargo.toml
@@ -6,7 +6,7 @@ publish = false
 
 [dependencies]
 aya = { version = ">=0.11", features=["async_tokio"] }
-aya-log = "0.1"
+aya-log = { git = "https://github.com/aya-rs/aya", branch = "main" }
 mkdir-common = { path = "../mkdir-common", features=["user"] }
 anyhow = "1.0.42"
 clap = { version = "3.1", features = ["derive"] }
```

The proper fix will be making a new release of aya-log ASAP.

**Comment by shenshouer** [comment] 2022-09-01 11:33
@vadorovsky Thank you for your changed, it worke ok now!

**Comment by vadorovsky** [comment] 2022-09-01 12:56
New aya-log was released and I can confirm that creating new projects works without patching now.

@shenshouer I would suggest you to re-create project from scratch, I hope you didn't write too much code yet. ;)

Closing. Feel free to re-open if there are any problems.

**Closed by vadorovsky** 2022-09-01 12:56 UTC
