### ISSUE TITLE
cargo generated projects depends on both git and v0.11

### ISSUE THREAD

**Issue by elbaro** [aya-rs/aya#568] opened 2023-04-09 00:03 UTC
The issue is similar to https://github.com/aya-rs/aya/issues/498 .
Following the guide, cargo-generated projects didn't work out of the box.
This was fixed by updating all aya-* packages to the git.

```
# aya = { version = ">=0.11", features = ["async_tokio"] }

aya = { git = "https://github.com/aya-rs/aya", branch = "main", features = [
    "async_tokio",
] }
```

**Comment by vadorovsky** [comment] 2023-04-09 06:49
Can you post the error you are getting, please?

We are using releases for user-space crates and git for eBPF crates. And that combination usually works (we are testing it in aya-template CI).

**Comment by elbaro** [comment] 2023-04-09 15:32
no compile error. uprobe + aya-log prints nothing.

```toml
# aya = { version = ">=0.11", features = ["async_tokio"] }
# aya-log = "0.1"
aya = { git = "https://github.com/aya-rs/aya", branch = "main", features = [
    "async_tokio",
] }
aya-log = { git = "https://github.com/aya-rs/aya", branch = "main" }
```

```rs
#[uprobe(name=..)] pub fn ..() { aya_log_ebpf::info!(&ctx, "enter");}
#[uretprobe(name=..)] pub fn ..() { aya_log_ebpf::info!(&ctx, "exit");}
```

**Comment by vadorovsky** [comment] 2023-04-09 17:58
Sorry, I can't reproduce your problem.

I tried creating a new uprobe project literally now. I provided the following parameters:

![aya-uprobe](https://user-images.githubusercontent.com/34685103/230788646-b91be5f2-c275-4821-b8dd-5cc791e5a7e7.png)

I didn't touch the versions, so it uses a stable release in user-space crate:

```
❯ cat foo/Cargo.toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = { version = ">=0.11", features=["async_tokio"] }
aya-log = "0.1"
clap = { version = "4.1", features = ["derive"] }
foo-common = { path = "../foo-common", features = ["user"] }
anyhow = "1"
env_logger = "0.10"
libc = "0.2"
log = "0.4"
tokio = { version = "1.25", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }

[[bin]]
name = "foo"
path = "src/main.rs"
```

And git depenfencies in the eBPF crate:

```
❯ cat foo-ebpf/Cargo.toml
[package]
name = "foo-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
foo-common = { path = "../foo-common" }

[[bin]]
name = "foo"
path = "src/main.rs"

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[workspace]
members = []
```

And it produces the expected output when running with `RUST_LOG=info cargo xtask run`:

![aya-libc-malloc](https://user-images.githubusercontent.com/34685103/230788807-491606a7-82f1-40c3-a1bc-f3d538fa7c56.png)

**Comment by vadorovsky** [comment] 2023-04-09 18:01
So please:

* Try creating the project from scratch (with `aya-generate`) and see if it causes any problems again.
  * If it works, it means that your broken project has some other issue and we can try to nail it down.
  * If it doesn't work, please come back with the exact commands and parameters you used, publishing the code would be very helpful and appreciated.

**Comment by elbaro** [comment] 2023-04-13 21:06
I also couldn't reproduce in a simpler program. Can you try this:

1. spawn mysqld
```sh
docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql
```

2. get pid and symbol name
```sh
❯ ps -e | grep mysqld  
  22612 ?        00:10:53 mysqld  # get pid
❯ objdump -tT /proc/22612/exe | rg dispatch_com
```


3. update attach info
```rs
    program.load()?;
    program.attach(
        Some("_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command"),
        0,
        "/proc/22612/exe",
        opt.pid,
    )?;

    info!("Waiting for Ctrl-C...");
```

4. add logging to ebpf
```rs
#[uprobe(name = "aya_568")]
pub fn aya_568(ctx: ProbeContext) -> u32 {
    aya_log_ebpf::info!(&ctx, "entered");
    match try_aya_568(ctx) {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}
```

5. fire queries. attaches well but no print
```sh
❯ cargo xtask build-ebpf    
❯ RUST_LOG=info cargo xtask run

❯ mysql -h 127.0.0.1 -u root -p
# type my-secret-pw
# type "select * from users;"
```

6. update aya, aya-log to git and repeat 5

**Comment by tamird** [comment] 2023-07-19 00:49
@elbaro it sounds like your problem was fixed by using the versions from git, and since https://github.com/aya-rs/aya-template/commit/3013ab506d511e572a7e03bbaf0417f41a4af124 all the versions in the template are from git. Please let me know if your problems remain unaddressed.

**Closed by tamird** 2023-07-19 00:49 UTC
