### ISSUE TITLE
aya-log panics when logging [u8;6] without format argument 

### ISSUE THREAD

**Issue by arctic-alpaca** [aya-rs/aya#513] opened 2023-02-02 08:20 UTC
Using aya-log to log a `[u8;6]` compiles and leads to a runtime panic if no format argument (e.g. `:mac`) is provided.

Example:
`info!(&ctx, "received a packet: {}", [0_u8;6]);` 

Error: 
```thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/arctic-alpaca/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.13/src/lib.rs:110:45```

Used a newly created xdp project from the template to reproduce.

**Comment by alessandrod** [comment] 2023-02-07 22:28
@vadorovsky when you get a chance could you look into this?

**Comment by Hanaasagi** [comment] 2023-04-13 12:15
@alessandrod @vadorovsky  Hi, I think I understand why the error was thrown. Firstly, the `write` function is implemented for the `[u8; 6]` type, as shown here: 

https://github.com/aya-rs/aya/blob/23ce42da6843b04fae4de40f4471565491b51109/aya-log-common/src/lib.rs#L191-L195

This writes the type of the field and some other information, which is then retrieved when formatting the string, as shown here:

https://github.com/aya-rs/aya/blob/23ce42da6843b04fae4de40f4471565491b51109/aya-log/src/lib.rs#L463-L465

Because `{}` is used in `info!(&ctx, "received a packet: {}", [0_u8;6]);`, the `last_hint` variable is `None`, and an error is thrown when formatting, as shown here:

https://github.com/aya-rs/aya/blob/23ce42da6843b04fae4de40f4471565491b51109/aya-log/src/lib.rs#L217-L231

 And currently, it seems that only `{:mac}` or `{:MAC}` can be used for output. I think we could add a `DebugFormatter` with  `{:?}` format syntax or modify the` DefaultFormatter` to support this.

**Comment by Hanaasagi** [comment] 2023-04-19 15:43
Please give me some feedback. If it would be helpful, I would be happy to take on the responsibility of addressing this issue.

**Comment by alessandrod** [comment] 2023-04-20 22:36
I think the issue is here https://github.com/aya-rs/aya/blob/23ce42da6843b04fae4de40f4471565491b51109/aya-log/src/lib.rs#L115 ? We shouldn't unwrap

**Comment by Hanaasagi** [comment] 2023-04-21 11:43
Indeed, `unwrap` is not appropriate here, but it is not the root cause of this bug because `Err` has already occurred. As I mentioned in my previous response, the error thrown by `info!(&ctx, "received a packet: {}", [0_u8;6]);` is due to the lack of a defined `DefaultFormatter` processing logic for the `[u8;6]` type. Therefore, I think resolving this issue depends on whether code like `info!("{}", [0_u8;6])` is supported.

- If it is valid, then a `DefaultFormatter`  should be added for the `[u8;6]` type, for example:


```Rust
impl Formatter<[u8; 6]> for DefaultFormatter; {
    fn format(v: [u8; 6]) -> String {
        // e.g.
        format!("{:?}", v)
    }
}

```

- If it is invalid, then the timing of throwing the error should be moved to the proc macro. The error should be thrown during compile time rather than runtime.

Here is an example code that moves the error timing to compile time:

https://github.com/aya-rs/aya/compare/main...Hanaasagi:aya:example

**Comment by vadorovsky** [comment] 2023-05-15 11:10
@Hanaasagi that's right, thanks for debugging that!

I think we shouldn't support `info!("{}", [0_u8;6])` - `std` formatter in Rust doesn't support it either:

```
error[[E0277]](https://doc.rust-lang.org/stable/error_codes/E0277.html): `[u8; 6]` doesn't implement `std::fmt::Display`
 --> src/main.rs:2:20
  |
2 |     println!("{}", [0u8; 6]);
  |                    ^^^^^^^^ `[u8; 6]` cannot be formatted with the default formatter
```

So I like your second option - moving the error to proc macro. Happy to see that you started working on it! Would you like to submit a pull request?

**Comment by Hanaasagi** [comment] 2023-05-16 01:45
Sure, I will open a pull request to validate this in proc macro.

**Closed** 2023-05-21 07:08 UTC
Labels: bug, aya-log
